fluentassertions/fluentassertions.analyzers

src/FluentAssertions.BestPractices/Tips/Collections/CollectionShouldOnlyHaveUniqueItemsByComparer.cs

Codefix for CollectionShouldOnlyHaveUniqueItemsByComparer

---

src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldHaveCount.cs

added support for #12

---

src/FluentAssertions.Analyzers.Tests/Tips/NullConditionalAssertionTests.cs
src/FluentAssertions.Analyzers/Constants.cs
src/FluentAssertions.Analyzers/FluentAssertions.Analyzers.nuspec
src/FluentAssertions.Analyzers/Tips/NullConditionalAssertionAnalyzer.cs

[Feature] null conditional assertion

---

src/FluentAssertions.Analyzers.Tests/FluentAssertions.Analyzers.Tests.csproj
src/FluentAssertions.Analyzers/FluentAssertions.Analyzers.csproj
src/FluentAssertions.Analyzers/Tips/NullConditionalAssertionAnalyzer.cs

updated NuGet packages versions

---

src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
src/FluentAssertions.Analyzers/Tips/Collections/CollectionAnalyzer.cs
src/FluentAssertions.Analyzers/Tips/Numerics/NumericAnalyzer.cs
src/FluentAssertions.Analyzers/Tips/Numerics/NumericShouldBeApproximately.cs
src/FluentAssertions.Analyzers/Tips/Strings/StringAnalyzer.cs
src/FluentAssertions.Analyzers/Utilities/FluentAssertionsAnalyzer.cs

Fixed expression bodied function crashing analyzers

---

appveyor.yml
build.cake
src/FluentAssertions.Analyzers.Tests/TestAttributes.cs

upload test results to appveyor

---

src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
src/FluentAssertions.Analyzers/Tips/Dictionaries/DictionaryAnalyzer.cs
src/FluentAssertions.Analyzers/Tips/Dictionaries/DictionaryShouldContainKey.cs
src/FluentAssertions.Analyzers/Tips/Dictionaries/DictionaryShouldContainKeyAndValue.cs
src/FluentAssertions.Analyzers/Tips/Dictionaries/DictionaryShouldContainPair.cs
src/FluentAssertions.Analyzers/Tips/Dictionaries/DictionaryShouldContainValue.cs
src/FluentAssertions.Analyzers/Tips/Dictionaries/DictionaryShouldNotContainKey.cs
src/FluentAssertions.Analyzers/Tips/Dictionaries/DictionaryShouldNotContainValue.cs
src/FluentAssertions.Analyzers/Utilities/FluentAssertionsAnalyzer.cs

fixed dictionary analyzers analyzing everything

---

src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldNotContainProperty.cs

fixed CollectionShouldNotContainProperty being too aggresive

---

src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs

added test case

---

src/FluentAssertions.Analyzers/Utilities/FluentAssertionsCSharpSyntaxVisitor.cs

InvalidOperationException with indexer

---

src/FluentAssertions.Analyzers.Tests/GenerateCode.cs
src/FluentAssertions.Analyzers.Tests/Tips/AsyncVoidTests.cs
src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
src/FluentAssertions.Analyzers/Constants.cs
src/FluentAssertions.Analyzers/Tips/AsyncVoid.cs

async void analyzer

---

src/FluentAssertions.Analyzers.Tests/FluentAssertions.Analyzers.Tests.csproj

Addresses the small issue we had for Tests assembly. 
#54

Move tests to .NET Core 3.0

---

README.md

Add documentation for running tests

---

src/FluentAssertions.Analyzers/FluentAssertions.Analyzers.csproj

Target library to latest net standard

---

src/FluentAssertions.Analyzers.Tests/FluentAssertions.Analyzers.Tests.csproj

Update Tests to netcore3.1

---

.github/workflows/ci.yml

add github action for CI

---

README.md

Update README.md - use github actions badge

---

.github/workflows/ci.yml
src/FluentAssertions.Analyzers.Tests/FluentAssertions.Analyzers.Tests.csproj
src/FluentAssertions.Analyzers/FluentAssertions.Analyzers.csproj

add net6 to TargetFrameworks

---

src/FluentAssertions.Analyzers.Tests/GenerateCode.cs
src/FluentAssertions.Analyzers.Tests/Tips/MsTestTests.cs
src/FluentAssertions.Analyzers/Tips/MsTest/MsTestBase.cs
src/FluentAssertions.Analyzers/Tips/Xunit/XunitBase.cs
src/FluentAssertions.Analyzers/Utilities/FluentAssertionsAnalyzer.cs

Detect testing libraries namespace in nested namespaces

---

src/FluentAssertions.Analyzers.Tests/Tips/MsTestTests.cs
src/FluentAssertions.Analyzers/Utilities/FluentAssertionsAnalyzer.cs

152 nested namespaces support fix

---

README.md

Update README.md - smaller icon

---

src/FluentAssertions.Analyzers/Constants.cs

Fixes https://github.com/fluentassertions/fluentassertions.analyzers/issues/165.

Change diagnostic IDs

---

src/FluentAssertions.Analyzers/Tips/MsTest/MsTestBase.cs
src/FluentAssertions.Analyzers/Tips/ShouldEquals.cs
src/FluentAssertions.Analyzers/Utilities/MemberValidator.cs
src/FluentAssertions.Analyzers/Utilities/TypesExtensions.cs

Based on https://github.com/dotnet/roslyn-analyzers/issues/3427.

Fix RS1024 warnings

---

src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
src/FluentAssertions.Analyzers/Utilities/Expressions.cs

fix: wrap with ParenthesizedExpression when casting the subject

---

src/FluentAssertions.Analyzers/FluentAssertions.Analyzers.csproj

chore: update analyzers project to dotnet6

---

src/FluentAssertions.Analyzers.Tests/DiagnosticVerifier.cs
src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
src/FluentAssertions.Analyzers/Tips/MsTest/MsTestBase.cs
src/FluentAssertions.Analyzers/Tips/Xunit/XunitBase.cs
src/FluentAssertions.Analyzers/Utilities/FluentAssertionsAnalyzer.cs

feat: verify assertion type and module

---

src/FluentAssertions.Analyzers/FluentAssertions.Analyzers.csproj

Reverts fluentassertions/fluentassertions.analyzers#184

Revert "chore: update analyzers project to dotnet6"

---

src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
src/FluentAssertions.Analyzers/Constants.cs
src/FluentAssertions.Analyzers/Tips/Xunit/AssertNotNull.cs
src/FluentAssertions.Analyzers/Tips/Xunit/AssertNull.cs

feat: add xunit Null assertions

---

src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
src/FluentAssertions.Analyzers/Tips/Collections/CollectionAnalyzer.cs

feat: enable collection analyzers for any collection including dictionaries

---

src/FluentAssertions.Analyzers.Tests/GenerateCode.cs
src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
src/FluentAssertions.Analyzers/Tips/Collections/CollectionAnalyzer.cs
src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldContainSingle.cs
src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldHaveElementAt.cs
src/FluentAssertions.Analyzers/Tips/Dictionaries/DictionaryAnalyzer.cs
src/FluentAssertions.Analyzers/Tips/Exceptions/ExceptionAnalyzer.cs
src/FluentAssertions.Analyzers/Tips/Numerics/NumericAnalyzer.cs
src/FluentAssertions.Analyzers/Tips/Numerics/NumericShouldBeApproximately.cs
src/FluentAssertions.Analyzers/Tips/Strings/StringAnalyzer.cs
src/FluentAssertions.Analyzers/Tips/Xunit/XunitBase.cs
src/FluentAssertions.Analyzers/Utilities/FluentAssertionsAnalyzer.cs
src/FluentAssertions.Analyzers/Utilities/TypesExtensions.cs

feat: support collection analyzers for arrays

---

README.md

- add @Porges https://github.com/microsoft/onefuzz/pull/3314
- add @TheCakeIsNaOH https://github.com/chocolatey/choco/pull/2908

docs: add more example usages

---

src/FluentAssertions.Analyzers.Tests/Tips/MsTestTests.cs

feat: add support for mstest Assert.IsInstanceOfType<T>

---

src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
src/FluentAssertions.Analyzers/Constants.cs
src/FluentAssertions.Analyzers/Tips/Xunit/AssertEmpty.cs

add support for xunit StringAsserts Empty

---

src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
src/FluentAssertions.Analyzers/Constants.cs
src/FluentAssertions.Analyzers/Tips/Xunit/AssertEmpty.cs
src/FluentAssertions.Analyzers/Tips/Xunit/AssertEndsWith.cs

add support for xunit StringAsserts EndsWith

---

src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
src/FluentAssertions.Analyzers/Constants.cs
src/FluentAssertions.Analyzers/Tips/Xunit/AssertStartsWith.cs

add support for xunit StringAsserts StartsWith

---

src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
src/FluentAssertions.Analyzers/Tips/Xunit/AssertDoesNotContain.cs

add support for xunit SetAsserts DoesNotContain

---

src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
src/FluentAssertions.Analyzers/Constants.cs
src/FluentAssertions.Analyzers/Tips/Xunit/AssertIsType.cs

related to https://github.com/fluentassertions/fluentassertions.analyzers/issues/146

add support for xunit TypeAsserts IsType

---

src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldHaveCount.cs
src/FluentAssertions.Analyzers/Tips/Strings/StringAnalyzer.cs

bugfix: fix string analyzers array complex type ignoring

---

src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs

tests: reproduce issue #276

---

src/FluentAssertions.Analyzers/Tips/DiagnosticMetadata.cs

bugfix: fix docs for issue #301

---

src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
src/FluentAssertions.Analyzers/Tips/FluentAssertionsOperationAnalyzer.cs

bugfix: fix analyzer for issue #300 and #299

---

src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
src/FluentAssertions.Analyzers/Tips/FluentAssertionsAnalyzer.cs

chore: bugfix/309 more than one dimension array

---

docs/FluentAssertionsAnalyzer.md
src/FluentAssertions.Analyzers.FluentAssertionAnalyzerDocs/FluentAssertionsAnalyzerTests.cs
src/FluentAssertions.Analyzers.FluentAssertionAnalyzerDocsGenerator/DocsGenerator.cs

docs: add TOC
