- src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
- src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
- src/FluentAssertions.Analyzers/Tips/Collections/CollectionShouldHaveElementAt.cs
This fixes #44 (thanks for the pointer of where to fix it!)
> Ignore dictionary types from HaveElementAt

- src/FluentAssertions.Analyzers.Tests/DiagnosticVerifier.cs
- src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
- src/FluentAssertions.Analyzers/Utilities/FluentAssertionsAnalyzer.cs
closes #49 
When running the analyzers on my project using VS 2017 (version 15.7.4), I encountered two null-reference exceptions. This PR fixes those.
> Fix null-reference exception

- src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
- src/FluentAssertions.Analyzers/Utilities/VariableNameExtractor.cs
closes #58
Since SymbolInfo is a struct, there's no need to null check that, however, if the default value is returned then the SymbolInfo.Symbol will be null, causing a NullReferenceException (not sure what about the code seems to trigger it, just trial and error)
> Check for no SymbolInfo for variables

- src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
- src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
- src/FluentAssertions.Analyzers/Utilities/FluentAssertionsCSharpSyntaxVisitor.cs
> fixed CollectionShouldOnlyHaveUniqueItemsByComparer gives invalid code

- src/FluentAssertions.Analyzers.Tests/FluentAssertions.Analyzers.Tests.csproj
- src/FluentAssertions.Analyzers.Tests/GenerateCode.cs
- src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
- src/FluentAssertions.Analyzers/Constants.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertEqual.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertNotEqual.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertNotStrictEqual.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertStrictEqual.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/XunitBase.cs
- src/FluentAssertions.Analyzers/Utilities/Expressions.cs
- src/FluentAssertions.Analyzers/Utilities/MemberValidator.cs
- src/FluentAssertions.Analyzers/Utilities/SemanticModelTypeExtensions.cs
> Add xunit equality assert analyzers

- src/FluentAssertions.Analyzers.Tests/Tips/MsTestTests.cs
- src/FluentAssertions.Analyzers/Tips/MsTest/AssertAreEqual.cs
- src/FluentAssertions.Analyzers/Tips/MsTest/AssertAreNotEqual.cs
- src/FluentAssertions.Analyzers/Utilities/ArgumentValidator.cs
- src/FluentAssertions.Analyzers/Utilities/MemberValidator.cs
> Issue 171 - when expect value is null object

- src/FluentAssertions.Analyzers.Tests/Tips/MsTestTests.cs
- src/FluentAssertions.Analyzers/Tips/MsTest/AssertAreEqual.cs
- src/FluentAssertions.Analyzers/Utilities/ArgumentValidator.cs
> fix: support first argument being the null keyword

- src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertEqual.cs
> add support for xunit StringAsserts Equals

- src/FluentAssertions.Analyzers.Tests/DiagnosticVerifier.cs
- src/FluentAssertions.Analyzers/Tips/MsTest/AssertIsFalse.cs
- src/FluentAssertions.Analyzers/Tips/MsTest/AssertIsTrue.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertNotEqual.cs
> bugfix: fix DiagnosticId for AssertIsFalse & AssertIsTrue

- src/FluentAssertions.Analyzers.Tests/DiagnosticVerifier.cs
- src/FluentAssertions.Analyzers.Tests/GenerateCode.cs
- src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertContains.cs
- src/FluentAssertions.Analyzers/Utilities/ArgumentValidator.cs
> add support for xunit SetAsserts Contains

- src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
- src/FluentAssertions.Analyzers/Constants.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertSubset.cs
> add support for xunit SetAsserts Subset

- src/FluentAssertions.Analyzers.Tests/DiagnosticVerifier.cs
- src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
- src/FluentAssertions.Analyzers/Constants.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertIsAssignableFrom.cs
> add support for xunit TypeAsserts IsAssignableFrom

- src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
- src/FluentAssertions.Analyzers/Constants.cs
- src/FluentAssertions.Analyzers/Tips/MsTest/AssertIsInstanceOfType.cs
- src/FluentAssertions.Analyzers/Tips/MsTest/AssertIsNotInstanceOfType.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertIsAssignableFrom.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertIsNotAssignableFrom.cs
- src/FluentAssertions.Analyzers/Utilities/TestingLibraryCodeFixBase.cs
> add support for xunit TypeAsserts IsNotAssignableFrom

- src/FluentAssertions.Analyzers.Tests/DiagnosticVerifier.cs
- src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertIsAssignableFrom.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertIsNotAssignableFrom.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertIsNotType.cs
- src/FluentAssertions.Analyzers/Tips/Xunit/AssertIsType.cs
- src/FluentAssertions.Analyzers/Utilities/Expressions.cs
- src/FluentAssertions.Analyzers/Utilities/TestingLibraryCodeFixBase.cs
After applying code fixes to transform XUnit asserts to fluent assertions I got some compilation errors. Some parenthesis were missing when the expression tested was complex.
Note:  The tests were not properly testing the code source after the code fix is applied, I re-enabled it but some tests were failing so I added a `'#if TO_BE_FIXED`
> Fix missing parenthesis after applying XUnit code fixes

- src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
- src/FluentAssertions.Analyzers/Tips/FluentAssertionsOperationAnalyzer.cs
> bugfix: Do not report fluentassertion diagnostic when there is a condition expression before the Should invocation

- src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
- src/FluentAssertions.Analyzers/Tips/XunitCodeFixProvider.cs
> feat: add xunit Assert.Equivalent

- src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
- src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
> bugfix: and test for #96

- src/FluentAssertions.Analyzers.Tests/Tips/SanityTests.cs
- src/FluentAssertions.Analyzers/Tips/DiagnosticMetadata.cs
- src/FluentAssertions.Analyzers/Tips/FluentAssertionsOperationAnalyzer.cs
> bugfix: fix issue 290

- src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
- src/FluentAssertions.Analyzers/Tips/FluentAssertionsAnalyzer.cs
> bugfix: limit CollectionShouldHaveCount_LengthShouldBe to one dimension arrays only 

- docs/MsTestAnalyzer.md
- src/FluentAssertions.Analyzers.FluentAssertionAnalyzerDocs/MsTestAnalyzerTests.cs
- src/FluentAssertions.Analyzers.Tests/Tips/MsTestTests.cs
- src/FluentAssertions.Analyzers/Tips/MsTestCodeFixProvider.cs
- src/FluentAssertions.Analyzers/Utilities/OperartionExtensions.cs
> feat: Rewrite parameters order when handling constant values in assertions

- README.md
- src/FluentAssertions.Analyzers.TestUtils/CsProjectArguments.cs
- src/FluentAssertions.Analyzers.TestUtils/TestAnalyzerConfigOptionsProvider.cs
- src/FluentAssertions.Analyzers.Tests/CodeFixVerifierArguments.cs
- src/FluentAssertions.Analyzers.Tests/DiagnosticVerifier.cs
- src/FluentAssertions.Analyzers.Tests/Tips/FluentAssertionsTests.cs
- src/FluentAssertions.Analyzers.Tests/Tips/MsTestTests.cs
- src/FluentAssertions.Analyzers.Tests/Tips/NullConditionalAssertionTests.cs
- src/FluentAssertions.Analyzers.Tests/Tips/NunitTests.cs
- src/FluentAssertions.Analyzers.Tests/Tips/XunitTests.cs
- src/FluentAssertions.Analyzers/Tips/AssertAnalyzer.cs
> tests: add examples for excluding assert methods from analyzer

- src/FluentAssertions.Analyzers.Tests/Tips/CollectionTests.cs
- src/FluentAssertions.Analyzers/Tips/FluentAssertionsAnalyzer.cs
- src/FluentAssertions.Analyzers/Utilities/OperartionExtensions.cs
@davidnmbond I think that #383 raised a core flaw in some of the assertions where we are not finding the descendent operation correctly
this PR will aim to fix this use-case
> feat: improve TryGetFirstDescendent logic - p1
